#!/usr/bin/python3
import nmap

# Variables
host = input("[+]Introduce la IP a escanear: ")
nm = nmap.PortScanner()
result = nm.scan(host,arguments="-n -Pn -T4")
puertos_abiertos="-p"
count=0
# Salida
print("Host: %s" % host)
print("State: %s" % nm[host].state())
print("--------------------------------")
for proto in nm[host].all_protocols():
    print('Protocol : %s' % proto)
    lport = nm[host][proto].keys()
    sorted(lport)
    for port in lport:
        print('port : %s\tstate : %s' % (port, nm[host][proto][port]['state']))
        if count==0:
            puertos_abiertos=puertos_abiertos+" "+str(port)
            count=1
        else:
            puertos_abiertos=puertos_abiertos + ","+str(port)
print("Puertos abiertos: "+puertos_abiertos+ " "+str(host))

